### PR TITLE
Add IOBooster: www.cd4o.com

### PR DESCRIPTION
**Pull request by LXY1226**
Just add a.a

### CODE REVIEW

**Comment by beyondgfw** [comment]
@LXY1226 Hello,
Thanks for opening this PR.
Safety note: You're submitting your changes with YOUR OWN IDENTITY, which is probably not good for your anonymity. Unless you're OK with this, please consider submit your changes as beyondgfw beyond.gfw.limit@gmail.com.

**Comment by lrinQVQ** [comment]
没有发现DNS污染和http阻挡 ip也可以联通

**Comment by LXY1226** [comment]
辽宁大连
IP:61.189.123.59
默认解析得到：31.13.83.16
ping不通，也无法访问

**Comment by lrinQVQ** [comment]
68.232.45.253 延迟更低

**Comment by LXY1226** [comment]
got it

**Comment by lrinQVQ** [comment]
XD修改下我直接commit吧

**Comment by LXY1226** [comment]
ok

**Comment by LXY1226** [comment]
emm好像改不掉了...

**Comment by lrinQVQ** [comment]
咩很简单 你只需要修改IP在提交一个commit就行

**Comment by lrinQVQ** [comment]
PR会自动更新的

**Comment by LXY1226** [comment]
Uploader：Something went really wrong, and we can’t process that file.
这让一个没装git4windows的很是难堪...QxQ

**Comment by lrinQVQ** [comment]
2333哇没事没事 我来改吧

**Comment by LXY1226** [comment]
Danke~

**Comment by lrinQVQ** [comment]
等待CI通过ing

**Pull request merged**
